name: flutter_ios_calculator
description: iOS 10 and iOS 11&
version: 0.1.0
homepage: https://github.com/ominibyte/flutter_ios_calculator.git


environment:
  sdk: '>=3.3.3 <4.0.0'
  

dependencies:
  flutter:
    sdk: flutter 
  intl: ^0.19.0
  flutter_device_type: ^0.4.0
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
